/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AuditLog {
  'id' : string,
  'action' : string,
  'hotelId' : [] | [bigint],
  'timestamp' : Time,
  'details' : string,
  'actorPrincipal' : Principal,
}
export interface Hotel { 'id' : bigint, 'name' : string, 'isActive' : boolean }
export interface Task {
  'id' : string,
  'status' : string,
  'title' : string,
  'creator' : Principal,
  'hotelIds' : Array<bigint>,
  'dueDate' : Time,
  'description' : string,
  'priority' : string,
  'assignedUsers' : Array<Principal>,
}
export interface TaskComment {
  'author' : Principal,
  'comment' : string,
  'taskId' : string,
  'timestamp' : Time,
}
export type Time = bigint;
export interface UserProfile {
  'username' : string,
  'password' : string,
  'name' : string,
  'role' : UserRole,
  'hotelId' : [] | [bigint],
  'isActive' : boolean,
  'securityManager' : [] | [string],
  'contactNumber' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addComment' : ActorMethod<[string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'assignTaskToAllUsersOfHotel' : ActorMethod<[string, bigint], undefined>,
  'assignTaskToAllUsersOfHotels' : ActorMethod<
    [string, Array<bigint>],
    undefined
  >,
  'assignUserToTask' : ActorMethod<[string, Principal], undefined>,
  'createManualHotel' : ActorMethod<[bigint, string, boolean], undefined>,
  'createTask' : ActorMethod<
    [string, string, Time, string, Array<bigint>],
    string
  >,
  'createUser' : ActorMethod<
    [
      Principal,
      string,
      string,
      [] | [bigint],
      [] | [string],
      [] | [string],
      string,
      UserRole,
    ],
    undefined
  >,
  'deleteHotel' : ActorMethod<[bigint], undefined>,
  'deleteUser' : ActorMethod<[Principal], undefined>,
  'getAllHotels' : ActorMethod<[], Array<Hotel>>,
  'getAllTasks' : ActorMethod<[], Array<Task>>,
  'getAllUsersProfiles' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'getAuditLogs' : ActorMethod<[], Array<AuditLog>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getTask' : ActorMethod<[string], [] | [Task]>,
  'getTaskComments' : ActorMethod<[string], Array<TaskComment>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateHotel' : ActorMethod<[bigint, string, boolean], undefined>,
  'updateUser' : ActorMethod<
    [
      Principal,
      string,
      string,
      [] | [bigint],
      [] | [string],
      [] | [string],
      boolean,
      string,
      UserRole,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];