/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const UserRole = IDL.Variant({ 'admin' : IDL.Null, 'user' : IDL.Null });
export const Hotel = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'isActive' : IDL.Bool,
});
export const Task = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'title' : IDL.Text,
  'creator' : IDL.Principal,
  'hotelIds' : IDL.Vec(IDL.Nat),
  'dueDate' : Time,
  'description' : IDL.Text,
  'priority' : IDL.Text,
  'assignedUsers' : IDL.Vec(IDL.Principal),
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'password' : IDL.Text,
  'name' : IDL.Text,
  'role' : UserRole,
  'hotelId' : IDL.Opt(IDL.Nat),
  'isActive' : IDL.Bool,
  'securityManager' : IDL.Opt(IDL.Text),
  'contactNumber' : IDL.Opt(IDL.Text),
});
export const AuditLog = IDL.Record({
  'id' : IDL.Text,
  'action' : IDL.Text,
  'hotelId' : IDL.Opt(IDL.Nat),
  'timestamp' : Time,
  'details' : IDL.Text,
  'actorPrincipal' : IDL.Principal,
});
export const TaskComment = IDL.Record({
  'author' : IDL.Principal,
  'comment' : IDL.Text,
  'taskId' : IDL.Text,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'assignTaskToAllUsersOfHotel' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'assignTaskToAllUsersOfHotels' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Nat)],
      [],
      [],
    ),
  'assignUserToTask' : IDL.Func([IDL.Text, IDL.Principal], [], []),
  'createManualHotel' : IDL.Func([IDL.Nat, IDL.Text, IDL.Bool], [], []),
  'createTask' : IDL.Func(
      [IDL.Text, IDL.Text, Time, IDL.Text, IDL.Vec(IDL.Nat)],
      [IDL.Text],
      [],
    ),
  'createUser' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Bool,
        IDL.Text,
        UserRole,
      ],
      [],
      [],
    ),
  'deleteHotel' : IDL.Func([IDL.Nat], [], []),
  'deleteUser' : IDL.Func([IDL.Text], [], []),
  'getAllHotels' : IDL.Func([], [IDL.Vec(Hotel)], ['query']),
  'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getAllUsersProfiles' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'getAuditLogs' : IDL.Func([], [IDL.Vec(AuditLog)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getTask' : IDL.Func([IDL.Text], [IDL.Opt(Task)], ['query']),
  'getTaskComments' : IDL.Func([IDL.Text], [IDL.Vec(TaskComment)], ['query']),
  'getUserProfile' : IDL.Func([IDL.Text], [IDL.Opt(UserProfile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateHotel' : IDL.Func([IDL.Nat, IDL.Text, IDL.Bool], [], []),
  'updateUser' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Bool,
        IDL.Text,
        UserRole,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const UserRole = IDL.Variant({ 'admin' : IDL.Null, 'user' : IDL.Null });
  const Hotel = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'isActive' : IDL.Bool,
  });
  const Task = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'title' : IDL.Text,
    'creator' : IDL.Principal,
    'hotelIds' : IDL.Vec(IDL.Nat),
    'dueDate' : Time,
    'description' : IDL.Text,
    'priority' : IDL.Text,
    'assignedUsers' : IDL.Vec(IDL.Principal),
  });
  const UserProfile = IDL.Record({
    'username' : IDL.Text,
    'password' : IDL.Text,
    'name' : IDL.Text,
    'role' : UserRole,
    'hotelId' : IDL.Opt(IDL.Nat),
    'isActive' : IDL.Bool,
    'securityManager' : IDL.Opt(IDL.Text),
    'contactNumber' : IDL.Opt(IDL.Text),
  });
  const AuditLog = IDL.Record({
    'id' : IDL.Text,
    'action' : IDL.Text,
    'hotelId' : IDL.Opt(IDL.Nat),
    'timestamp' : Time,
    'details' : IDL.Text,
    'actorPrincipal' : IDL.Principal,
  });
  const TaskComment = IDL.Record({
    'author' : IDL.Principal,
    'comment' : IDL.Text,
    'taskId' : IDL.Text,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'assignTaskToAllUsersOfHotel' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'assignTaskToAllUsersOfHotels' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Nat)],
        [],
        [],
      ),
    'assignUserToTask' : IDL.Func([IDL.Text, IDL.Principal], [], []),
    'createManualHotel' : IDL.Func([IDL.Nat, IDL.Text, IDL.Bool], [], []),
    'createTask' : IDL.Func(
        [IDL.Text, IDL.Text, Time, IDL.Text, IDL.Vec(IDL.Nat)],
        [IDL.Text],
        [],
      ),
    'createUser' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Bool,
          IDL.Text,
          UserRole,
        ],
        [],
        [],
      ),
    'deleteHotel' : IDL.Func([IDL.Nat], [], []),
    'deleteUser' : IDL.Func([IDL.Text], [], []),
    'getAllHotels' : IDL.Func([], [IDL.Vec(Hotel)], ['query']),
    'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getAllUsersProfiles' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'getAuditLogs' : IDL.Func([], [IDL.Vec(AuditLog)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getTask' : IDL.Func([IDL.Text], [IDL.Opt(Task)], ['query']),
    'getTaskComments' : IDL.Func([IDL.Text], [IDL.Vec(TaskComment)], ['query']),
    'getUserProfile' : IDL.Func([IDL.Text], [IDL.Opt(UserProfile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateHotel' : IDL.Func([IDL.Nat, IDL.Text, IDL.Bool], [], []),
    'updateUser' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Bool,
          IDL.Text,
          UserRole,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };